services:

  postgres:
    image: postgres:16
    
    container_name: garden-postgres

    environment:
      POSTGRES_DB: garden_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"
      
    volumes:
      - postgres_data:/var/lib/postgresql/data

  garden-api:
    build: .

    container_name: garden-api

    depends_on:
      - postgres

    ports:
      - "8082:8082"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/garden_management
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      
volumes:
  postgres_data:
